version: "3"

services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pact-broker:
    image: pactfoundation/pact-broker:2.79.1.0
    ports:
      - "9292:9292"
    depends_on:
      - postgres
    environment:
      PACT_BROKER_PORT: "9292"
      PACT_BROKER_DATABASE_URL: "postgres://postgres:password@postgres/postgres"
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SQL_LOG_LEVEL: DEBUG
      # PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES is only needed for docker-compose
      # because the database takes longer to start up than the puma process
      # Should not be needed in production.
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
      # The list of allowed base URLs (not setting this makes the app vulnerable to cache poisoning)
      # This allows the app to be addressed from the host from within another docker container correctly
      PACT_BROKER_BASE_URL: "https://localhost http://localhost http://localhost:9292 http://pact-broker:9292"
      PACT_BROKER_DISABLE_SSL_VERIFICATION: "true"
      # For CI: refer to (https://hub.docker.com/r/pactfoundation/pact-broker)
      PACT_BROKER_BASIC_AUTH_USERNAME: "d966ded9e2f54160a0a09fd4c9520543"
      PACT_BROKER_BASIC_AUTH_PASSWORD: "1b587a8bf460160d5c0da479b2dace88"
      # For developer
      # PACT_BROKER_BASIC_AUTH_READ_ONLY_USERNAME: "read-only-account"
      # PACT_BROKER_BASIC_AUTH_READ_ONLY_PASSWORD: "read-only-password"

volumes:
  postgres-volume:
